# Site settings
title: "Jektify"
email: william.costa.canin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jektify is a Gem for entering track, playlist, albums and artists in Jekyll templates.
# Urls production
# baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jektify.github.io" # the base hostname & protocol for your site.

# Change version!!!
header:
  name: "jektify"
  url_download: "https://rubygems.global.ssl.fastly.net/gems"
  lasted_version: "1.0.2"

# Build settings
destination: ./_site
markdown: kramdown
highlighter: pygments

# Permilink
permalink: /:title/

# Config Sass Jekyll
sass:
  sass_dir: _sass
  style: compressed

# Config for Compress HTML
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Excluded for build
exclude: ["_gems","Gemfile","*.lock","build","serve"]

plugins:
  - bootstrap


# ----------------------------------------------------------------------
# Jektify - Configuration for _config.yml
# Insert this code in your template
#
jektify:
  enable: true
  open: false
  toggle:
    enable: true
  spotify:
    user: williamcanin
    text: See me no Spotify
  sass:
    jekyll: true
    other:
      dir: "src/sass"
  title:
    enable: true
    text: "Jektify"
  description:
    enable: true
    text: |
      Jekyll plugin to generate html snippets for embedding Spotify Musics.
      To listen to the full song, open your Spotify and start these musics.
#
# ----------------------------------------------------------------------
